### ISSUE TITLE
Upload to Maven Central Repository 

### ISSUE THREAD

**Issue by Sanmoo** [raisercostin/yanfs#1]
Hello, @raisercostin 

Do you think this lib could be uploaded to an Online Repository?

Regards,

**Comment by raisercostin** [comment]
I released yanfs-1.3 sources included to bintray.

**Comment by mcacker** [comment]
If you did, they're no longer there

**Comment by raisercostin** [comment]
This is not accessible http://jcenter.bintray.com/com/sun/yanfs/1.3/ ?
