### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by abhijeet-adarsh** [raisercostin/yanfs#2]
Hi raisercostin,

I am facing the following issue after including yanfs dependency and JCentral repository in my project. 

> Failed to collect dependencies at com.sun:yanfs:jar:1.3: Failed to read artifact descriptor for com.sun:yanfs:jar:1.3: Could not find artifact org.raisercostin.utils:maven-defaults:pom:5 in bintray-jcenter (http://jcenter.bintray.com) 

Can you please guide if I am missing something?

thanks
Abhijeet

**Comment by raisercostin** [comment]
Probably I forgot to publish that version and got automatically discarded. I republished it now and is available at https://jcenter.bintray.com/org/raisercostin/utils/maven-defaults/5/ . You should try again and should work. Thanks.

**Comment by abhijeet-adarsh** [comment]
Thanks, it did work.
