### ISSUE TITLE
Other string encodings for file paths?

### ISSUE THREAD

**Issue by brunchboy** [raisercostin/yanfs#4]
I would love to be able to use this to talk to an embedded UDP NFSv2 server, but I can’t get it to work because the server requires mount paths and file paths to be sent in UTF-16BE. How can I configure that?

**Comment by brunchboy** [comment]
I’ve been able to hack it to do this, and successfully mount the server, but am running into other limitations of the server implementation, namely you cannot mount multi-directory paths, you must use NFS lookup to move from file handle to file handle, so I think I am going to have to roll my own NFS client implementation, unfortunately. I will submit a PR that fixes one of the open issues, however.

**Comment by raisercostin** [comment]
Hi, thanks for PR. Regarding the other question I'm not sure. I'm just managing this library that was starved to death on sourceforge before. If you find a way or a fix I'll be happy to merge it to the trunk.

**Comment by brunchboy** [comment]
It turns out that I can’t use this library for other reasons (the NFS implementation on the CDJs is very quirky, and cannot accept multi-directory paths, you need to use the NFS Lookup RPC), so I am having to write my own implementation at the level of XDR. I’ll close this because it’s probably not an issue for anyone else.
