### ISSUE TITLE
License category for YaNFS

### ISSUE THREAD

**Issue by manutripathi82** [raisercostin/yanfs#9]
Hi, I want to use the project in my application, but need to know under which license it comes. This is required for legal purpose in my organization.

**Comment by raisercostin** [comment]
I'm not entirely sure about the license. It might be BSD.

The project was started by Sun and there is a notice on all source files coming from them that suggests a very liberal license similar to BSD, apache, MIT.

See https://web.archive.org/web/20120103134830/http://blogs.oracle.com/shepler/entry/yanfs_is_the_new_webnfs and https://web.archive.org/web/20120922084738/http://java.net/projects/yanfs
